### ISSUE TITLE
Unable to pass parameter to monitoring script

### ISSUE THREAD

**Issue by michruch** [squaredup/Community.PowerShellMonitoring.MP#6]
Hi,

I am unable to pass argument to my PowerShell Script Two State Monitor. The saved event shows empty value. Here is my monitor fragment:

<ScriptName>MSP_Cluster_Health_check.ps1</ScriptName>
<ScriptBody>#Cluster Health

#param($computerName) 

$api = New-Object -comObject “MOM.ScriptAPI”  
$PropertyBag = $api.CreatePropertyBag()

$api.LogScriptEvent("ThisIsMyParameter",9999,2,"$computerName")

$PropertyBag.AddValue(“ComputerName”,$computerName)

$PropertyBag

</ScriptBody>
<Arguments>$Target/Property[Type="MicrosoftWindowsLibrary7585010!Microsoft.Windows.Computer"]/PrincipalName$</Arguments>

In general does not matter which parameter I try to use, nothing gets passed.

Is passing arguments to script even possible in this MP?

 thanks in advance for any suggestion

**Comment by michruch** [comment]
Of course param() is not commented, opposite to my example above

**Comment by shadeon** [comment]
It's possible, you just have to receive all parameters as a string value named `Arguments` due to limitations of the templates.  The templates should already have `param([string]$Arguments)` specified, so just change it back to that.

If you need to pass multiple args, just add a delimiter between each and use the string.split method in your script to extract them.

It's also worth noting that you can add dynamic property references directly into the script, and SCOM will inject them prior to running the script on each target, so the below also works perfectly fine:

`$computerName = '$Target/Property[Type="MicrosoftWindowsLibrary7585010!Microsoft.Windows.Computer"]/PrincipalName$'`

**Comment by michruch** [comment]
Hi Shadeon,

This works fine. Thank you for your help
